bootstrap_barrio_library: production
bootstrap_barrio_sidebar_position: both
bootstrap_barrio_content_offset: 0
bootstrap_barrio_sidebar_first_width: 3
bootstrap_barrio_sidebar_first_offset: 0
bootstrap_barrio_sidebar_second_width: 4
bootstrap_barrio_sidebar_second_offset: 0
bootstrap_barrio_fluid_container: 0
bootstrap_barrio_button: 1
bootstrap_barrio_button_size: ''
bootstrap_barrio_button_outline: 0
bootstrap_barrio_navbar_toggle: navbar-toggleable-lg
bootstrap_barrio_navbar_container: '0'
bootstrap_barrio_navbar_top_position: ''
bootstrap_barrio_navbar_top_color: ''
bootstrap_barrio_navbar_top_background: ''
bootstrap_barrio_navbar_position: ''
bootstrap_barrio_navbar_color: ''
bootstrap_barrio_navbar_background: ''
bootstrap_barrio_messages_widget: alerts
bootstrap_barrio_radio: custom
bootstrap_barrio_checkbox: switch
bootstrap_barrio_select: custom
bootstrap_barrio_file: custom
bootstrap_barrio_system_messages: messages_white
bootstrap_barrio_table_hover: 1
bootstrap_barrio_table_style: table-striped
_core:
  default_config_hash: XVyjqKNCH498_gwxI4iS26Liob1z90U28Oaw1CHOJzc
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://logo_1.png'
favicon:
  use_default: false
  path: 'public://logo_2.png'
  mimetype: image/png
bootstrap_barrio_region_clean_top_header: '0'
bootstrap_barrio_region_class_top_header: row
bootstrap_barrio_region_clean_top_header_form: '0'
bootstrap_barrio_region_class_top_header_form: row
bootstrap_barrio_region_clean_header: '1'
bootstrap_barrio_region_class_header: ''
bootstrap_barrio_region_clean_header_form: '0'
bootstrap_barrio_region_class_header_form: row
bootstrap_barrio_region_clean_primary_menu: '1'
bootstrap_barrio_region_class_primary_menu: ''
bootstrap_barrio_region_clean_secondary_menu: '0'
bootstrap_barrio_region_class_secondary_menu: row
bootstrap_barrio_region_clean_page_top: '0'
bootstrap_barrio_region_class_page_top: row
bootstrap_barrio_region_clean_page_bottom: '0'
bootstrap_barrio_region_class_page_bottom: row
bootstrap_barrio_region_clean_highlighted: '1'
bootstrap_barrio_region_class_highlighted: ''
bootstrap_barrio_region_clean_featured_top: '0'
bootstrap_barrio_region_class_featured_top: row
bootstrap_barrio_region_clean_breadcrumb: '1'
bootstrap_barrio_region_class_breadcrumb: ''
bootstrap_barrio_region_clean_content: '1'
bootstrap_barrio_region_class_content: ''
bootstrap_barrio_region_clean_sidebar_first: '1'
bootstrap_barrio_region_class_sidebar_first: ''
bootstrap_barrio_region_clean_sidebar_second: '1'
bootstrap_barrio_region_class_sidebar_second: ''
bootstrap_barrio_region_clean_featured_bottom_first: '0'
bootstrap_barrio_region_class_featured_bottom_first: row
bootstrap_barrio_region_clean_featured_bottom_second: '0'
bootstrap_barrio_region_class_featured_bottom_second: row
bootstrap_barrio_region_clean_featured_bottom_third: '0'
bootstrap_barrio_region_class_featured_bottom_third: row
bootstrap_barrio_region_clean_footer_first: '0'
bootstrap_barrio_region_class_footer_first: row
bootstrap_barrio_region_clean_footer_second: '0'
bootstrap_barrio_region_class_footer_second: row
bootstrap_barrio_region_clean_footer_third: '0'
bootstrap_barrio_region_class_footer_third: row
bootstrap_barrio_region_clean_footer_fourth: '0'
bootstrap_barrio_region_class_footer_fourth: row
bootstrap_barrio_region_clean_footer_fifth: '0'
bootstrap_barrio_region_class_footer_fifth: row
bootstrap_barrio_sidebar_collapse: 0
bootstrap_barrio_navbar_top_navbar: 0
bootstrap_barrio_navbar_top_class: ''
bootstrap_barrio_navbar_class: ''
bootstrap_barrio_navbar_top_affix: 0
bootstrap_barrio_navbar_affix: 0
bootstrap_barrio_sidebar_first_affix: 0
bootstrap_barrio_sidebar_second_affix: 0
bootstrap_barrio_scroll_spy: ''
bootstrap_barrio_google_fonts: ''
bootstrap_barrio_bootstrap_icons: 0
bootstrap_barrio_icons: ''
bootstrap_barrio_table_head: ''
bootstrap_barrio_region_clean_menu_1: 0
bootstrap_barrio_region_class_menu_1: row
bootstrap_barrio_region_clean_menu_2: 0
bootstrap_barrio_region_class_menu_2: row
bootstrap_barrio_region_clean_menu_3: 0
bootstrap_barrio_region_class_menu_3: row
bootstrap_barrio_region_clean_menu_4: 0
bootstrap_barrio_region_class_menu_4: row
bootstrap_barrio_region_clean_menu_5: 0
bootstrap_barrio_region_class_menu_5: row
bootstrap_barrio_region_clean_page_title: 0
bootstrap_barrio_region_class_page_title: row
bootstrap_barrio_region_clean_front_full: 0
bootstrap_barrio_region_class_front_full: row
bootstrap_barrio_region_clean_front_ecom: 0
bootstrap_barrio_region_class_front_ecom: row
bootstrap_barrio_region_clean_testi: 0
bootstrap_barrio_region_class_testi: row
bootstrap_barrio_region_clean_partners: 0
bootstrap_barrio_region_class_partners: row
bootstrap_barrio_region_clean_satff_gall: 0
bootstrap_barrio_region_class_satff_gall: row
bootstrap_barrio_region_clean_map: 0
bootstrap_barrio_region_class_map: row
bootstrap_barrio_region_clean_footer_new: 0
bootstrap_barrio_region_class_footer_new: row
